name: Test and Lint

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          frontend/package-lock.json
          backend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend && npm ci
        cd ../backend && npm ci
    
    - name: Lint Frontend
      run: |
        cd frontend
        npm run lint
    
    - name: Test Frontend
      run: |
        cd frontend
        npm run test:ci
    
    - name: Lint Backend
      run: |
        cd backend
        npm run lint
    
    - name: Test Backend
      run: |
        cd backend
        npm run test:ci
    
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
  
  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install detect-secrets
      run: pip install detect-secrets
    
    - name: Run secrets scan
      run: detect-secrets scan --baseline .secrets.baseline